### ISSUE TITLE
Could you list some pros and cons of React/Redux ecosystem?

### ISSUE THREAD

**Issue by whitechdevs** [josephj/products-app#23]

**Comment by josephj** [comment]
Correct if I am wrong. Are you talking about React ecosystem or React/Redux specifically? I feel the later one is probably a bit narrow and people start to migrate to GraphQL. Let me know if my context is wrong. 

**Pros**

* It's diverse and open. You can select the component which fits your preferences. You can use `redux-observable` if you prefer RxJS rather than promise. You can use `redux-saga` if you feel `redux-observable` is way too powerful than needed. 
* It's opt-in. You can start to adopt it while you feel you really need to solve specific problem. "You don't need redux". Even `setState` sometimes is good enough for small apps. We also use `setState` a lot since not all UI states are reusable across the components. 
* It encourages to find the next best practices and patterns (e.g. webpack, CSS-in-JS, FSM) and possibly improve React itself (e.g. React.lazy)
* More fun since it always have some new thoughts and new solutions. 
* More strong community support and solutions are usually mature than its competitors. (Vue Weex vs React Native) 

**Cons**

* Causing more issues while solving problems - Introducing a new technology could lead to have more issues. For example, after introducing the Redux. What's the best approach to organise our store, reducer, and actions? It produces a lot boilerplate code. We spent 2 years to figure out how and also introduced several new tools (dot-props-immutable, ducks pattern, and redux-actions) It definitely solves our props passing problem but the cost of flexibility is unexpected higher.
* On-boarding new devs might take more time since their previous team is very easy to have different approaches. 
* Less productive somehow - React is not a framework which helps to you build scalable app directly. For scalability you have to keep integrate different stuffs. 
* Difficult to understand things comprehensively since all components keep to have some breaking changes. Most of time we just make a tool works rather than understanding this tool thoroughly
